version: '3'

services:
  restaurant-donations-food-storage-service:
    container_name: restaurant-donations-food-storage-service
    image: restaurant-donations-food-storage-service
    build: .
    environment:
      KAFKA_BROKER: ''
      KAFKA_USERNAME: ''
      KAFKA_PASSWORD: ''
      FOOD_MARKETPLACE_URL: ''
      DB_HOST_NAME: ''
      DB_PORT: 5432
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_NAME: ''
    ports:
      - 3002:3002
